#pragma once

enum {
    RECORDER_IFACE_CMD_GET_MODE,
    RECORDER_IFACE_CMD_SET_MODE,
    RECORDER_IFACE_CMD_START,
    RECORDER_IFACE_CMD_STOP,
    RECORDER_IFACE_CMD_SET_STREAM,
    MAIN_SET_START,
    MAIN_SET_STOP,
    MAIN_GET_PROCESSING
};

enum {
    RECORDER_MODE_BASEBAND,
    RECORDER_MODE_AUDIO
};

enum DemodID {
    RADIO_DEMOD_NFM,
    RADIO_DEMOD_WFM,
    RADIO_DEMOD_AM,
    RADIO_DEMOD_DSB,
    RADIO_DEMOD_USB,
    RADIO_DEMOD_CW,
    RADIO_DEMOD_LSB,
    RADIO_DEMOD_RAW,
    _RADIO_DEMOD_COUNT,
};
/*
enum {
    RADIO_IFACE_MODE_NFM,
    RADIO_IFACE_MODE_WFM,
    RADIO_IFACE_MODE_AM,
    RADIO_IFACE_MODE_DSB,
    RADIO_IFACE_MODE_USB,
    RADIO_IFACE_MODE_CW,
    RADIO_IFACE_MODE_LSB,
    RADIO_IFACE_MODE_RAW
};

const char* demodModeList[] = {
    "NFM",
    "WFM",
    "AM",
    "DSB",
    "USB",
    "CW",
    "LSB",
    "RAW"
};

const char* demodModeListTxt = "NFM\0WFM\0AM\0DSB\0USB\0CW\0LSB\0RAW\0";

const char* bandListTxt = " 1000\0 6250\0 12500\0 25000\0 50000\0 100000\0 220000\0";
*/